Update documentation for 0.3 version
satnogs/satnogs-client pull request #249
Opened 2017-03-20 11:57 UTC by adamkalis

These are some change for 0.3 documentation. It is not complete, I'll add some more changes soon after I'll be able to test them in a rpi device.

2017-03-20 21:57 UTC, acinonyx requested changes

2017-03-20 21:57 UTC, acinonyx commented on doc/architecture.rst
> + * Starts/Stops gnuradio script (``gr-satnogs``), which collects the data.
`GNU Radio` instead of  `gnuradio`

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +1. You have a raspberry pi 3 with external power (5v, 2A).
`Raspberry` instead of `raspberry`, `Pi` instead of `pi` and `V` instead of `v` for volts.

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +2. USB keyboard, HDMI screen, HDMI cable, network cable (wifi isn't working on fedora for now) and a Class 10 SDHC card at least 8GB
`Fedora` and `Wi-Fi`

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +3. One of the following sdr devices: rtl-sdr or usrpb200.
`RTL-SDR` and `USRP B200`

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +4. You have an account on either network.satnogs.org or network-dev.satnogs.org and have 1) your ground station ID number, 2) your API key
Web services need to stand out somehow from normal text. Also, inline list is awkward.

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +**Step 1.1:** Download fedora minimal or server rpi image (current 25) from `Arm Fedora Project <https://arm.fedoraproject.org/>`_ (server edition provides a nice web interface, admin console, with s
`RPi`, `ARM` and `SSH`

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +**Step 1.2:** Connect sdcard to your computer/laptop and prepare it as described at `Fedora Wiki <https://fedoraproject.org/wiki/Raspberry_Pi#Preparing_the_SD_card>`_ (don't forget to `resize the roo
`SD card`

2017-03-20 21:57 UTC, acinonyx commented on doc/raspi-install.rst
> +**Step 1.3:** Attach sdcard to your rpi, plug in the hdmi cable, keyboard and ethernet and turn on the hdmi screen. Plug rpi to the power source.
`RPi` and `HDMI`

2017-03-21 10:36 UTC, comzeradd commented on doc/raspi-install.rst
> +4. You have an account on either network.satnogs.org or network-dev.satnogs.org and have 1) your ground station ID number, 2) your API key
Using backticks should probably do the trick. Like `this`.

2017-03-28 17:50 UTC, acinonyx approved these changes

2017-03-28 17:51 UTC, acinonyx commented
@adamkalis could you please rebase?

2017-03-29 07:43 UTC, adamkalis commented
@acinonyx, rebase is done.

I am working on remaining tasks:
* Supervisor instructions need some updates.
* Add systemd instructions.

2017-03-29 17:15 UTC, merged